### ISSUE TITLE
Speedhack

### ISSUE THREAD

**Issue by chaowoses** [Enchoseon/better-edpuzzle-userscript#2]
How do I enable and disable the speedhack? It got enabled and I can't understand anything anymore

**Comment by Enchoseon** [comment]
Adjust your speed to whatever is comfortable in the `config` variable ([here](https://github.com/Enchoseon/better-edpuzzle-userscript/blob/main/better-edpuzzle-userscript.user.js#L19)).

The default value is `2` times speed, but you can set it to `1` to disable it.
